### PR TITLE
fix README.md - add correct path at script and Step 0 to make the scripts executable.

### PR DESCRIPTION
**Pull request by ksemele**
After moving `README.md`, someone forgot to change the script path.

### CODE REVIEW

**Comment by ksemele** [comment]
Also, I added a few commands at `Step 0` to make the scripts executable.

**Comment by fireflycons** [comment]
Hi @ksemele 

I have updated the permissions of those scripts in the repo. Sync the master branch with your fork, pull it again and check that the shell scripts are now executable.

If so, then you can remove `step 0` from your change and I will re-review it.

Thanks

**Comment by ksemele** [comment]
@fireflycons yeah, thx. I was thinking about just changing the permissions for the scripts, but I was embarrassed) I thought that maybe I was missing something.
I removed `Step 0` from PR.

**Comment by fireflycons** [comment]
No need to be embarrassed 😄 
Just that the original commit was done on Windows and there it is required to do a 
```
git update-index --chmod=+x`
```
on anything that should be cloned as executable.

**Pull request merged**
