### PR TITLE
Typo

### LINKED ISSUE #123: Typo
Hello,

There is a Minor Typo in  in docs/07-Security/15-API-Groups.md

### LINKED ISSUE #125: Minor correction
Hello,

There is minor correction in docs/07-Security/11-Certificate-API.md at line 64

### PR DESCRIPTION
**Pull request by PoojaPatel-IIT**
Fixes #123, Fixes #125

### CODE REVIEW

**Comment by PoojaPatel-IIT** [comment]
Fixes #125

**Review by Tej-Singh-Rana — APPROVED** [review]
LGTM

**Comment by PoojaPatel-IIT** [comment]
Thank you @Tej-Singh-Rana  and @fireflycons

**Comment by Tej-Singh-Rana** [comment]
Thanks for your contribution. 👍

**Pull request merged**
