### PR TITLE
Apple m1 support

### PR DESCRIPTION
**Pull request by jtprichett**
Hello!

I recently took the [Kubernetes for the Absolute Beginners - Hands-on](https://www.udemy.com/course/learn-kubernetes/) course, and working through section 12, the provided repo Vagrantfile does not work for Apple M1 Pro machines.

I completed the section with no issues with the updated Vagrantfile and decided to contribute it back to the repository for others. 

I also created a complementary repository to install vagrant and VMware fusion for folks needing guidance/help since many of the resources are stale.

Here is a link to that repo: https://github.com/jtprichett/setup-vagrant-apple-m1

Let me know what I can do to contribute.

### CODE REVIEW

**Comment by csalvador-nr** [comment]
I tried to set it up in my M1 Macbook but when I try to vagrant up I face this issue:
```
An error occurred while executing 'vmrun',  a utility for controlling
VMware machines. The command and output are below:

Command: ["-T", "player", "list", {:notify=>[:stdout, :stderr]}]

Stdout: Invalid host type 'player' specified
Error: The operation is not supported

Stderr: 
```

Do you have any idea what could be wrong? I installed VMWare Fusion 13 correctly

**Comment by csbertran** [comment]
I tried to set it up in my M1 Macbook but when I try to vagrant up I face this issue:
```
An error occurred while executing 'vmrun',  a utility for controlling
VMware machines. The command and output are below:

Command: ["-T", "player", "list", {:notify=>[:stdout, :stderr]}]

Stdout: Invalid host type 'player' specified
Error: The operation is not supported

Stderr: 
```

Do you have any idea what could be wrong? I installed VMWare Fusion 13 correctly

**Comment by csbertran** [comment]
> Hello!
> 
> I recently took the [Kubernetes for the Absolute Beginners - Hands-on](https://www.udemy.com/course/learn-kubernetes/) course, and working through section 12, the provided repo Vagrantfile does not work for Apple M1 Pro machines.
> 
> I completed the section with no issues with the updated Vagrantfile and decided to contribute it back to the repository for others.
> 
> I also created a complementary repository to install vagrant and VMware fusion for folks needing guidance/help since many of the resources are stale.
> 
> Here is a link to that repo: https://github.com/jtprichett/setup-vagrant-apple-m1
> 
> Let me know what I can do to contribute.

Hi @jtprichett I tried to set it up in my M1 Macbook but when I try to vagrant up I face this issue:
```
An error occurred while executing 'vmrun',  a utility for controlling
VMware machines. The command and output are below:

Command: ["-T", "player", "list", {:notify=>[:stdout, :stderr]}]

Stdout: Invalid host type 'player' specified
Error: The operation is not supported

Stderr: 
```

Do you have any idea what could be wrong? I installed VMWare Fusion 13 correctly

**Comment by fireflycons** [comment]
Hi @csbertran  @jtprichett 

We have recently released an alternative way to set up a kubeadm cluster on M1 using multipass
https://github.com/kodekloudhub/certified-kubernetes-administrator-course/tree/master/apple-silicon

**Pull request closed without merging**
